name: E2E

# когда запускаем( когда push в main)
on:
  push:
    branches:
      - main  # ← добавил пробел после дефиса
  workflow_dispatch:

# Описываем джобы которые запускаем когда "push в main")
jobs:  # ← этот элемент должен быть на том же уровне, что и 'on' и 'name'
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Установка node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Установка пакетов
        run: npm ci
      - name: Установка браузеров
        run: npx playwright install --with-deps
      - name: Запуск тестов
        run: npx playwright test
      - name: Запуск генерации в одном allure файле
        run: npx allure awesome ./allure-results --single-file
        if: always()
        continue-on-error: true
      #  сохраняю результаты
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        continue-on-error: true
        with:
            name: allure-report
            path: allure-report
            retention-days: 30







